### PR TITLE
Fix license

### PR DESCRIPTION
**Pull request by Kezii**

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]
Legitimate

**Review by ghost — APPROVED** [review]

**Comment by gottardini** [comment]
Legit

**Comment by vm03** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Logga

**Review by MrQubo — APPROVED** [review]

**Review by S0yKaf — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Sid-Sun** [comment]
That's NEVER gonna happen

**Review by gottardini — APPROVED** [review]

**Comment by RoestVrijStaal** [comment]
I understand the current license is meh. 

But Apache 2.0, 3-clause BSD, ISC or zlib license would  be far better than any copyleft license to preserve the liberty for all actors instead of the liberty of some "freedom" fundamentalists.

**Comment by Vykook** [comment]
Oh no, GPL is cancer of free software.

**Comment by vbextreme** [comment]
@RoestVrijStaal

is freedom not to be free?

**Review by vbextreme — APPROVED** [review]

**Comment by lucatarik** [comment]
+1

**Comment by Testato** [comment]
+1

**Review by Testato — APPROVED** [review]

**Review by lucatarik — APPROVED** [review]

**Comment by ghost** [comment]
+1

**Review by ghost — APPROVED** [review]

**Comment by xdb6f** [comment]
+++

**Comment by xdb6f** [comment]
ADD
## THIS
### FUCKING
**LICENSE**

**Comment by ghost** [comment]
N

**Comment by ghost** [comment]
Apple fix this bug 🤣

**Review by ghost — APPROVED** [review]

**Comment by RoestVrijStaal** [comment]
@vbextreme 

Please mind i've put the word "freedom" in double quotes because what FSF means with that word contrasts with what Average Joe means with the word.

Anyway my point I wanted to make with my comment: 

- Apache 2.0, 3-clause BSD, ISC or zlib :arrow_right: Everyone and everything benefits from the contributions and is free to grab the code and -depending on what the license permits or/and restricts- do whatever they like. 
- GPL/LGPL/AGPL/copyleft :arrow_right: Only copylefted projects and actors benefit from contributions. The rest have to reinvent the wheel again from scratch. The freedom of the non-copylefted is restricted due the GPL/LGPL/AGPL.

**Comment by LLJY** [comment]
+1

**Review by LLJY — APPROVED** [review]

**Comment by vbextreme** [comment]
start by thanking Apple to get the pull back open and giving us free to express ourselves. This is very important for open source. Thank you.

@RoestVrijStaal, the GPL is FREEDOM FOR ALL, not only for developer or for big company who wants to use it.

A recent example of side effect that brings the opensource is Minix, Minix is opensource for Tanenbaum, is opensource for Intel, but NOT is opensource for all user that use Minix in your pc. This is opensource?
For me the code must be open to everyone, not only for one or two people.

I hope that Apple find the method of released open code for everyone without impact about their finances.

**Comment by veggero** [comment]
+1

**Comment by laura240406** [comment]
+1

**Pull request closed without merging**
