### PR TITLE
Correct acronym for XNU

### PR DESCRIPTION
**Pull request by ErikHumphrey**

### CODE REVIEW

**Comment by TheIcyStar** [comment]
XNU could be a [recursive acronym](https://en.wikipedia.org/wiki/Recursive_acronym), just like [PIP](https://en.wikipedia.org/wiki/Pip_(package_manager)) for Python is.
This change is very likely to be unnecessary.

**Comment by ErikHumphrey** [comment]
I am basing it upon Apple's [glossary](https://developer.apple.com/library/content/documentation/Porting/Conceptual/PortingUnix/glossary/glossary.html). It seems to be different from the acronym for GNU.

**Comment by 0xadada** [comment]
🤔

**Comment by CameronBanga** [comment]
I think this is wrong and should be rejected.

**Comment by Mardoxx** [comment]
Literally unusable.

**Comment by calumjames** [comment]
This doc also refers to macOS as OS X, which is now wrong, and it doesn’t mention Darwin’s use in watchOS and tvOS.

**Comment by oliverphardman** [comment]
This probably isn't worth merging for such a small issue.

**Review by nrebhun — APPROVED** [review]

**Review by hardikkaji — APPROVED** [review]

**Review by billinghamj — CHANGES_REQUESTED** [review]
👀

**Comment by breath103** [comment]
Did you even understand that this is homage of [GNU](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwixreCDpdLWAhVjjFQKHUnAAHsQFgg5MAI&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FGNU&usg=AOvVaw0nasIlYv4-BcJZB6cu2wyl)? obviously wrong change here

**Comment by nrebhun** [comment]
@breath103 As the author has already clarified:
> @ErikHumphrey:
> I am basing it upon Apple's [glossary](https://developer.apple.com/library/content/documentation/Porting/Conceptual/PortingUnix/glossary/glossary.html). It seems to be different from the acronym for GNU.

You and wikipedia are correct; GNU does stand for "GNU's Not Unix".

However, wikipedia correctly cites Apple's glossary (as of this writing) in stating XNU's expansion to be: **"X is Not Unix"**.

**Review by ghost — APPROVED** [review]

**Comment by dreness** [comment]
Fixed by 
https://github.com/apple/darwin-xnu/commit/5bbb823c13f3ab1ab58878f96b35433a29882676. I don't have privs in this repo to close the PR, though... @ErikHumphrey would you mind closing this? Thanks!

**Pull request closed without merging**
