### PR TITLE
Upgrade README

### PR DESCRIPTION
**Pull request by nrebhun**
### 🛠 this is very much a work-in-progress. 🛠 

I'm submitting my changes for review early, specifically to get community feedback.
I want to update the front-facing README to be as accessible as possible for others... and that's pretty hard to do in isolation.

Additionally, this incorporates the changes from #1 and #2, as I fully expect this to merge after those Pull Requests, and I don't want to have to deal with merge conflicts, however trivial they would be. Also, I want those folks to receive the credit they deserve for finding those changes. 🙂 

So! With that out of the way...

## ✅ Some of my objectives:
- Use of the [GFM spec](https://github.github.com/gfm/)
- Concise, articulate, and accurate language
- Style consistency, including:
    - Follow some max-line-length (currently at 132 characters, because of the `.clang-format` config's definition, but I'm not married to this number by any stretch)
    - Syntax highlighting on code snippets where reasonable
    - Indentation
    - "Internal" and "External" linking
        - "Internal" links bring readers to other places in the same doc, or to another file in this repo
        - "External" links bring readers to other websites entirely, either belonging to Apple or not

## ⚠️ Some things I know I'll need help with:
- **kernel concepts & fundamentals**; I have not developed kernel code before, and have only a high-level understanding of what most of the more technical stuff means. If I change the wording of an idea, and completely destroy the correct meaning, I want to hear about it.
- **linking to other docs/files**; some links left in this doc are either unused, or missing. There seem to be references to "Internal" files which no longer exist. Finding some equivalent is obviously more ideal than removing the link or concept entirely, but I concede this may be necessary at times.

## ⭐️ Requests to the Community:
- Let's localize this file! Accessibility means more than simply cleaning up language/grammar. I would help here, but I'm (sadly) not fluent in any natural languages beyond English.

---

I'm going to update this description as needed.

### CODE REVIEW

**Comment by max6cn** [comment]
Stop it.

**Comment by masters3d** [comment]
Suggestion: separate your content changes from your style changes into different commits. This will make the diff easier to read.

**Comment by nrebhun** [comment]
@masters3d Good idea! Thanks 🙂 
I'll do this asap!

**Review by ghost — APPROVED** [review]

**Review by jdilley — APPROVED** [review]

**Comment by ghost** [comment]
Certainly looks good.

**Review by ErikHumphrey — APPROVED** [review]

**Comment by casperes1996** [comment]
How would it be desirable to have potential translations into other languages? It's not a huge language, but I'd be able to offer a Danish translation. Would this be as a separate README-Danish.md or how would it be preferred? - That said I'm not really even sure this would be a good addition. For one thing, Danes are generally good at English, and for another, code itself should be consistent and adhere to English. We don't want to want up with variable names that come from many different languages. 
In any case, these commits look good to me overall.

**Comment by das** [comment]
sorry at present this repository is a pure mirror of opensource.apple.com and we are not able to accept community contributions for this project via github PR. Please use https://developer.apple.com/bug-reporting/ to submit your contributions.

**Pull request closed without merging**
