### PR TITLE
Updated XNU + OOB patches

### PR DESCRIPTION
**Pull request by userlandkernel**

### CODE REVIEW

**Comment by userlandkernel** [comment]
Nevermind, Apple doesn't patch it anyway

**Comment by npyl** [comment]
I will fork this into my Repo, and merge your PR... it will become a repo of xnu with community patches!

**Comment by userlandkernel** [comment]
Thank you!
I've always found that a great idea to have as it might help Apple in improving XNU stability and security faster.
Means zerodays can be patched before they even reach Apple Inc. haha

**Comment by npyl** [comment]
Merged! :)

**Pull request closed without merging**
