### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by behdaad**
Change "OS X" and "MacOS" to "macOS".
Change "I386" to "i386".
Change "X86_64" to "x86_64".

### CODE REVIEW

**Review by nrebhun — APPROVED** [review]

**Review by Knight1 — APPROVED** [review]
+1

**Comment by RoestVrijStaal** [comment]
Why? What's the added value of those changes? :confused:

**Comment by israelroldan** [comment]
Consistency with Apple branding and standard linux terminology from the looks of it.

**Review by ghost — APPROVED** [review]

**Comment by RoestVrijStaal** [comment]
@israelroldan Why should standard linux terminology apply to other *nixes code? That ad populum does not make sense.

**Review by indexerrowaty — APPROVED** [review]

**Comment by behdaad** [comment]
So it turns out my changes were already done in https://github.com/apple/darwin-xnu/commit/5bbb823c13f3ab1ab58878f96b35433a29882676, so no need for this PR anymore.

**Pull request closed without merging**
